//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinanceMarketMaker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCompleted
    {
        public int OrderCompletedId { get; set; }
        public string Username { get; set; }
        public string Pair { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountUSDT { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<decimal> WallBuy { get; set; }
        public Nullable<decimal> WallSell { get; set; }
        public Nullable<decimal> MinTickBuy { get; set; }
        public Nullable<decimal> MinTickSell { get; set; }
        public Nullable<decimal> TickUp { get; set; }
        public Nullable<decimal> ProfitPercentage { get; set; }
        public Nullable<decimal> ProfitUSDT { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
