//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinanceMarketMaker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRCode
    {
        public long QRCodeId { get; set; }
        public long UserId { get; set; }
        public byte[] Image { get; set; }
        public string Filename { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual User User { get; set; }
    }
}
