//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinanceMarketMaker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.QRCodes = new HashSet<QRCode>();
        }
    
        public long UserId { get; set; }
        public long ChatId { get; set; }
        public string Username { get; set; }
        public string ApiKey { get; set; }
        public string ApiSecret { get; set; }
        public bool EnableUpdate { get; set; }
        public System.DateTime Timestamp { get; set; }
        public decimal BTC { get; set; }
        public decimal ETH { get; set; }
        public string Exchange { get; set; }
        public decimal LTC { get; set; }
        public decimal USDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRCode> QRCodes { get; set; }
    }
}
