//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinanceMarketMaker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public int UserSettingsId { get; set; }
        public string ApiKey { get; set; }
        public string SecretKey { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<decimal> BTC { get; set; }
        public Nullable<decimal> ETH { get; set; }
        public Nullable<decimal> LTC { get; set; }
        public Nullable<decimal> USDT { get; set; }
    }
}
